const data = {
    products : [
        {
            _id: '1',
            name: 'Red Dress',
            category: 'dresses',
            images:'./images/p1.jpg',
            price:79,
            brand: 'vienna',
            rating : 4.5,
            numReviews: 13,
            description: 'hight quality product',
        },
        {
            _id: '2',
            name: 'Black Dress',
            category: 'dresses',
            images:'./images/p2.jpg',
            price:49,
            brand: 'h&m',
            rating : 3.5,
            numReviews: 12,
            description: 'hight quality product',
        },
        {
            _id: '3',
            name: 'Black Dress',
            category: 'dresses',
            images:'./images/p3.jpg',
            price:99,
            brand: 'zara',
            rating : 4.0,
            numReviews: 7,
            description: 'hight quality product',
        },
        {
            _id: '4',
            name: 'white Dress',
            category: 'dresses',
            images:'./images/p4.jpg',
            price:89,
            brand: 'terranova',
            rating : 4.5,
            numReviews: 18,
            description: 'hight quality product',
        },
        {
            _id: '5',
            name: 'white Dress',
            category: 'dresses',
            images:'./images/p5.jpg',
            price:79,
            brand: 'terranova',
            rating : 5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '6',
            name: 'Red Dress',
            category: 'dresses',
            images:'./images/p6.jpg',
            price:129,
            brand: 'zara',
            rating : 5,
            numReviews: 12,
            description: 'hight quality product',
        },
        {
            _id: '7',
            name: 'Red Dress',
            category: 'dresses',
            images:'./images/p7.jpg',
            price:49,
            brand: 'motivie',
            rating : 3.0,
            numReviews: 15,
            description: 'hight quality product',
        },
    ]
}

export default data;